version: "3.7"

########################### NETWORKS
networks:
  homeassistant:
    external: true

########################### SERVICES
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    networks:
      - homeassistant
    ports:
      - 8123:8123
      - 51827:51827
    volumes:
      - $DOCKERDIR/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
