[http.routers]
  [http.routers.jackett-rtr]
      entryPoints = ["https"]
      rule = "Host(`jackett.barinohub.com`)"
      service = "jackett-svc"
      middlewares = ["chain-oauth"]
      [http.routers.jackett-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.jackett-svc]
    [http.services.jackett-svc.loadBalancer]
      passHostHeader = true
      [[http.services.jackett-svc.loadBalancer.servers]]
        url = "http://192.168.1.200:9117"
