[http.routers]
  [http.routers.hydra-rtr]
      entryPoints = ["https"]
      rule = "Host(`hydra.barinohub.com`)"
      service = "hydra-svc"
      middlewares = ["chain-oauth"]
      [http.routers.hydra-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.hydra-svc]
    [http.services.hydra-svc.loadBalancer]
      passHostHeader = true
      [[http.services.hydra-svc.loadBalancer.servers]]
        url = "http://192.168.1.200:5076"
