[http.routers]
  [http.routers.transmission-vpn-rtr]
      entryPoints = ["https"]
      rule = "Host(`trans.barinohub.com`)"
      service = "transmission-vpn-svc"
      middlewares = ["chain-oauth"]
      [http.routers.transmission-vpn-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.transmission-vpn-svc]
    [http.services.transmission-vpn-svc.loadBalancer]
      passHostHeader = true
      [[http.services.transmission-vpn-svc.loadBalancer.servers]]
        url = "http://192.168.1.200:9091"
