[http.routers]
  [http.routers.radarr-rtr]
      entryPoints = ["https"]
      rule = "Host(`radarr.barinohub.com`)"
      service = "radarr-svc"
      middlewares = ["chain-oauth"]
      priority=99
      [http.routers.radarr-rtr.tls]
        certresolver = "dns-cloudflare"

  [http.routers.radarr-rtr-bypass]
      entryPoints = ["https"]
      rule = "Headers(`X-Api-Key`, `265325f7a6b14594a036470b3ecc5185`) || Query(`apikey`, `265325f7a6b14594a036470b3ecc5185`)"
      service = "radarr-svc"
      middlewares = ["chain-no-auth"]
      priority=100

[http.services]
  [http.services.radarr-svc]
    [http.services.radarr-svc.loadBalancer]
      passHostHeader = true
      [[http.services.radarr-svc.loadBalancer.servers]]
        url = "http://192.168.1.200:7979"
