[http.routers]
  [http.routers.sabnzb-rtr]
      entryPoints = ["https"]
      rule = "Host(`sabnzb.barinohub.com`)"
      service = "sabnzb-svc"
      middlewares = ["chain-oauth"]
      priority=99
      [http.routers.sabnzb-rtr.tls]
        certresolver = "dns-cloudflare"

  [http.routers.sabnzb-rtr-bypass]
      entryPoints = ["https"]
      rule = "Query(`apikey`, `72dad5ed4e5ee3150a53f54886462a4b`)"
      service = "sabnzb-svc"
      middlewares = ["chain-no-auth"]
      priority=100

[http.services]
  [http.services.sabnzb-svc]
    [http.services.sabnzb-svc.loadBalancer]
      passHostHeader = true
      [[http.services.sabnzb-svc.loadBalancer.servers]]
        url = "http://192.168.1.200:8081"
