http:
  routers:
    nd-desk-rtr:
      rule: Host(`nd-desk.{{ env "DOMAINNAME" }}`)
      service: nd-desk-svc
      entryPoints:
        - https
      middlewares:
        - chain-oauth
      tls:
        certresolver: dns-cloudflare

  services:
    nd-desk-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://192.168.1.200:19999'
