http:
  routers:
    jackett-rtr:
      rule: Host(`jackett.{{ env "DOMAINNAME" }}`)
      service: jackett-svc
      entryPoints:
        - https
      middlewares:
        - chain-oauth
      tls:
        certresolver: dns-cloudflare

  services:
    jackett-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://192.168.1.200:9117'

