[http.routers]
  [http.routers.desk-netdata-rtr]
      entryPoints = ["https"]
      rule = "Host(`desk-netdata.barinohub.com`)"
      service = "desk-netdata-svc"
      middlewares = ["chain-oauth"]
      [http.routers.desk-netdata-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.desk-netdata-svc]
    [http.services.desk-netdata-svc.loadBalancer]
      passHostHeader = true
      [[http.services.desk-netdata-svc.loadBalancer.servers]]
        url = "http://192.168.1.200:19998"
