version: "3.7"

networks:
  hass_bridge:
    driver: bridge
    attachable: true

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    depends_on:
      - mariadb
    restart: unless-stopped
    network_mode: host
    ports:
      - $HASS_PORT:8123/tcp
    volumes:
      - $DOCKERDIR/homeassistant:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

  hass-configurator:
    container_name: hass-configurator
    image: causticlab/hass-configurator-docker:latest
    depends_on:
      - homeassistant
    restart: unless-stopped
    networks:
      - hass_bridge
    ports:
      - $HASS_CONFIGURATOR_PORT:3218/tcp
    volumes:
      - $DOCKERDIR/configurator:/config
      - $DOCKERDIR/homeassistant:/hass-config
      - $SSHDIR/id_ed25519:/root/.ssh/id_ed25519:ro
      - $SSHDIR/id_ed25519.pub:/root/.ssh/id_ed25519.pub:ro
      - $SSHDIR/known_hosts:/root/.ssh/known_hosts:rw

  mariadb:
   container_name: mariadb
   image: mariadb:latest
   restart: unless-stopped
   networks:
     - hass_bridge
   ports:
     - $MARIADB_PORT:3306
   volumes:
     - $DOCKERDIR/mariadb:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
     MYSQL_USER: homeassistant
     MYSQL_PASSWORD: $MYSQL_PASSWORD
     MYSQL_DATABASE: homeassistant

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - hass_bridge
    ports:
      - $PHPMYADMIN_PORT:80
    environment:
      - PMA_ARBITRARY=1

  # influxdb:
  #   container_name: influxdb
  #   #image: influxdb
  #   image: influxdb:1.8.4-alpine
  #   restart: unless-stopped
  #   networks:
  #     - hass_bridge
  #   ports:
  #     - "$INFLUXDB_PORT:8086"
  #   # user: '99'
  #   volumes:
  #     - $DOCKERDIR/influxdb:/var/lib/influxdb
  #     - $DOCKERDIR/influxdb/conf:/etc/influxdb

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:latest
  #   restart: unless-stopped
  #   networks:
  #     - hass_bridge
  #   ports:
  #     - "$GRAFANA_PORT:3000"
  #   #user: '99'
  #   volumes:
  #     - $DOCKERDIR/grafana:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ALLOW_EMBEDDING=true
  #     #- GF_SECURITY_COOKIE_SAMESITE=none
  #     - GF_INSTALL_PLUGINS=neocat-cal-heatmap-panel

  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    networks:
      - hass_bridge
    ports:
      - $NODERED_PORT:1880
    volumes:
      - $DOCKERDIR/nodered:/data

