homeassistant: !include homeassistant.yaml

logger:
  default: info

default_config:

hacs:
  token: !secret  hacs_token
  sidepanel_title: Community

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
