name: Arroyo
latitude: !secret latitude
longitude: !secret longitude
elevation: !secret elevation
unit_system: imperial
time_zone: America/Chicago
# customize: !include customize.yaml
allowlist_external_dirs:
  - /data/homeassistant
  - /home/homeassistant/maps
# auth_providers: !include auth_providers.yaml
# external_url: !secret remote_base
# internal_url: !secret local_base
